[package]
name = "nm-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nm-proto = { workspace = true }
nm-core = { workspace = true }
nm-transport = { workspace = true }
nm-gossip = { workspace = true }
nm-crypto = { workspace = true }
nm-entity = { workspace = true }
prost = "0.14"
dashmap = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
serde_json = { workspace = true }
