[package]
name = "im-client"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
im-proto = { workspace = true }
im-core = { workspace = true }
im-transport = { workspace = true }
im-gossip = { workspace = true }
im-crypto = { workspace = true }
im-entity = { workspace = true }
prost = "0.14"
dashmap = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
