[package]
name = "nm-transport"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
nm-proto = { workspace = true }
nm-core = { workspace = true }
iroh = { workspace = true }
prost = "0.14"
serde_json = { workspace = true }
tokio = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
